# Generated by Django 3.1.3 on 2023-03-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_remove_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
    ]
